"""add phone and is_onboarded

Revision ID: 764af9beae2d
Revises: e9819e7a4f9f
Create Date: 2026-03-26 19:34:36.866221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764af9beae2d'
down_revision: Union[str, Sequence[str], None] = 'e9819e7a4f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
