"""make freelancer_id nullable

Revision ID: e592f87855d5
Revises: 764af9beae2d
Create Date: 2026-04-02 00:50:31.660028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e592f87855d5'
down_revision: Union[str, Sequence[str], None] = '764af9beae2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'freelancer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'freelancer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
