"""add resolved to dispute status enum

Revision ID: e9819e7a4f9f
Revises: f1fb32045cbc
Create Date: 2026-03-10 00:11:19.069484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9819e7a4f9f'
down_revision: Union[str, Sequence[str], None] = 'f1fb32045cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
